### ISSUE TITLE
Copy to different targets

### ISSUE THREAD

**Issue by Nixola** [astrand/xclip#32]
Right now, the ``-t`` option allows you to select a "target" for whatever you're copying, but what if I wanted to copy more than one thing to more than one target, as browsers do when you copy stuff from a webpage, copying both the HTML to text/html and the unformatted text to text/plain?

**Comment by lilydjwg** [comment]
I tried to do `xclip -t text/plain a -t text/html b` but a get all of `a` and `b` in HTML. Hope this can be added.

**Comment by Nixola** [comment]
I don't know if it's against this repo's guidelines (for I haven't found any), but I'd like to bump the issue since it hasn't had any answer in months.

**Comment by astrand** [comment]
The problem is just that xclip, just like most other open source projects, depends on volunteer work. Unfortunately, it seems like this particular problem is not a showstopper for me or any other developer, thus no fix has been created. Depending on your skills, you might try to fix the problem yourself, or raise funds via for example Bountysource or similar services.

**Comment by MyriaCore** [comment]
Just wanna bump this, multiple `-t` options would be super useful, I ended up finding this issue via [this SO comment](https://unix.stackexchange.com/q/375002#comment667121_375002). I'm willing to poke around in the code and submit a PR if necessary, although I'm not too familiar with programming for X.

**Comment by vvs-** [comment]
I think it should not be too difficult. Just needs modification of the command line parsing. So that each specified file would be stored into each target sequentially and the rest would go to default target as usual.

But as **astrand** said above there is just not enough motivation for that change yet.

**Comment by phillipberndt** [comment]
I thought I'd need this, too, but then noticed while thinking further about it that the only must-have addition for me is to set the `STRING` target together with other text formats like `text/html`, since some applications won't allow you to paste rich text unless the `STRING` target is set as well. I just implemented that and opened PR #142.

**Comment by jamietanna** [comment]
Thanks very much for the work on this folks - I see  https://github.com/astrand/xclip/pull/142 is merged, should this be closed?

This seems to work now via that new option (building from the unreleased changes), and i.e. allows pasting into Slack, whereas before it was not possible 🚀

**Comment by Nixola** [comment]
It doesn't solve my issue as stated, but it does solve the specific issue I was having.
